// Higher level --------> Translator------> Low level languages............

// Print ------- Pre - Cursive ----------> Cursive.........

// Procedural ---> C,Basic,PASCAL............c++ also.....
// Functional ---Pure Functions........... JavScript,Python..........
// OO Oriented Paradigm.............Java,C++..........

// Attributes(Features)......,Methods(Function).........

// Classes.........., Objects..........
// Platform Independent........
// Simple and easy...........
// Large standard library........

// DSA, DEV,Big DATA............
// JAVA ARCHITECTURE............
// JDK,JVM,JRE..........



// Source code ---> compile....>Byte code----> Interpret(By JVM)------->Machine Code----->       
// Compile ONCE RUN ANYWHERE..........

// lowercase 
// uppercase
// camel case .......... all functions and variables are ........
// constant .........Upper snake case with underscore (_)  ...........
// Pascal case .....class ...
// packages ............lowercase................

// variables ......
// no number, no space,   no keyword as variable, variables as camel case and meaningful words, 

// Identifiers,begin with  A-Z / a-z / $ / _  , No keyword are  used,case sensitive,
public class main{
    public static void main(String[] args){
        System.out.println("Hello World!");
        int i = 12;
        i = 1234;
        System.out.println(i);
        // string r = "dhjebj";
    }
}