// Higher level --------> Translator------> Low level languages............

// Print ------- Pre - Cursive ----------> Cursive.........

// Procedural ---> C,Basic,PASCAL............c++ also.....
// Functional ---Pure Functions........... JavScript,Python..........
// OO Oriented Paradigm.............Java,C++..........

// Attributes(Features)......,Methods(Function).........

// Classes.........., Objects..........
// Platform Independent........
// Simple and easy...........
// Large standard library........

// DSA, DEV,Big DATA............
// JAVA ARCHITECTURE............
// LDK,JVM,JRE..........



// Source code ---> compile....>Byte code----> Interpret(By JVM)------->Machine Code----->       
// Compile ONCE RUN ANYWHERE..........


public class main{
    public static void main(String[] args){
        System.out.println("Hello World!");
        int i = 12;
        System.out.println(i);
        // string r = "dhjebj";
    }
}