// Higher level --------> Translator------> Low level languages............

// Print ------- Pre - Cursive ----------> Cursive.........

// Procedural ---> C,Basic,PASCAL............
// Functional ---Pure Functions...........
// OO Oriented Paradigm.............